const dog = `In 1758, the taxonomist Linnaeus published in his Systema Naturae the classification of species. Canis is a Latin word meaning dog,[30] and under this genus he listed the dog-like carnivores including domestic dogs, wolves, and jackals. He classified the domestic dog as Canis familiaris (Linnaeus, 1758) and on the next page as a separate species he classified the wolf as Canis lupus (Linnaeus, 1758).[2] In 1926, the International Commission on Zoological Nomenclature (ICZN) ruled in Opinion 91 that the domestic dog Canis familiaris (Linnaeus, 1758) be placed on its official list.[3] In 1957, the ICZN ruled in Opinion 451 that Canis dingo (Meyer, 1793) was the name to be used for the dingo and that this be placed on its official list.[31] These are the scientific names for the dog and dingo that appear on the Official Lists and Indexes of Names in Zoology of the ICZN.[32]

In 1978, a review to reduce the number species listed under genus Canis proposed that "Canis dingo is now generally regarded as a distinctive feral domestic dog. Canis familiaris is used for domestic dogs, although taxonomically it should probably be synonymous with Canis lupus."[33] In 1982, the first edition of Mammal Species of the World included a note under Canis lupus with the comment: "Probably ancestor of and conspecific with the domestic dog, familiaris. Canis familiaris has page priority over Canis lupus, but both were published simultaneously in Linnaeus (1758), and Canis lupus has been universally used for this species".[34] In the same year, an application was made to the ICZN to reclassify the dingo to Canis lupus dingo because it was proposed that the wolf (Canis lupus) was the ancestor of dogs and dingoes, however the application was rejected.[35]

In 2003, the ICZN ruled in its Opinion 2027 that the "name of a wild species...is not invalid by virtue of being predated by the name based on a domestic form." Additionally, the ICZN placed the taxon Canis lupus as a conserved name on the official list under this opinion.[36] In the third edition of Mammal Species of the World published in 2005, the mammalogist W. Christopher Wozencraft listed under the wolf Canis lupus what he proposed to be two subspecies: "familiaris Linneaus, 1758 [domestic dog]" and "dingo Meyer, 1793 [domestic dog]",[a] with the comment "Includes the domestic dog as a subspecies, with the dingo provisionally separate – artificial variants created by domestication and selective breeding. Although this may stretch the subspecies concept, it retains the correct allocation of synonyms."[1] Although the earliest use of the name "dingo" was Canis familiaris dingo (Blumenbach, 1780),[37] Wozencraft attributed it to Meyer from 1793 without comment.[38]

This classification by Wozencraft is hotly debated by zoologists.[35] Mathew Crowther, Stephen Jackson and Colin Groves disagree with Wozencraft and argue that based on ICZN Opinion 2027, the implication is that a domestic animal cannot be a subspecies.[39][40] Crowther, Juliet Clutton-Brock and others argue that because the dingo differs from wolves by behavior, morphology, and that the dingo and dog do not fall genetically within any extant wolf clade, that the dingo should be considered the distinct taxon Canis dingo.[41][35][40] Jackson and Groves regard the dog Canis familiaris as a taxonomic synonym for the wolf Canis lupus with them both equally ranked at the species level. They also disagree with Crowther, based on the overlap between dogs and dingoes in their morphology, in their ability to easily hybridize with each other, and that they show the signs of domestication by both having a cranium of smaller capacity than their progenitor, the wolf. Given that Canis familiaris (Linnaeus, 1758) has date priority over Canis dingo (Meyer, 1793), they regard the dingo as a junior taxonomic synonym for the dog Canis familiaris.[39] Gheorghe Benga and others support the dingo as a subspecies of the dog from the earlier Canis familiaris dingo (Blumenbach, 1780).[42][43][44] Xiaoming Wang and Richard H. Tedford proposed that the dog should be classified as Canis lupus familiaris under the Biological Species Concept and Canis familiaris under the Evolutionary Species Concept.[4]`;
const cat = `In 1758, the taxonomist Linnaeus published in his Systema Naturae the classification of species. Canis is a Latin word meaning dog,[30] and under this genus he listed the dog-like carnivores including domestic dogs, wolves, and jackals. He classified the domestic dog as Canis familiaris (Linnaeus, 1758) and on the next page as a separate species he classified the wolf as Canis lupus (Linnaeus, 1758).[2] In 1926, the International Commission on Zoological Nomenclature (ICZN) ruled in Opinion 91 that the domestic dog Canis familiaris (Linnaeus, 1758) be placed on its official list.[3] In 1957, the ICZN ruled in Opinion 451 that Canis dingo (Meyer, 1793) was the name to be used for the dingo and that this be placed on its official list.[31] These are the scientific names for the dog and dingo that appear on the Official Lists and Indexes of Names in Zoology of the ICZN.[32]

In 1978, a review to reduce the number species listed under genus Canis proposed that "Canis dingo is now generally regarded as a distinctive feral domestic dog. Canis familiaris is used for domestic dogs, although taxonomically it should probably be synonymous with Canis lupus."[33] In 1982, the first edition of Mammal Species of the World included a note under Canis lupus with the comment: "Probably ancestor of and conspecific with the domestic dog, familiaris. Canis familiaris has page priority over Canis lupus, but both were published simultaneously in Linnaeus (1758), and Canis lupus has been universally used for this species".[34] In the same year, an application was made to the ICZN to reclassify the dingo to Canis lupus dingo because it was proposed that the wolf (Canis lupus) was the ancestor of dogs and dingoes, however the application was rejected.[35]

In 2003, the ICZN ruled in its Opinion 2027 that the "name of a wild species...is not invalid by virtue of being predated by the name based on a domestic form." Additionally, the ICZN placed the taxon Canis lupus as a conserved name on the official list under this opinion.[36] In the third edition of Mammal Species of the World published in 2005, the mammalogist W. Christopher Wozencraft listed under the wolf Canis lupus what he proposed to be two subspecies: "familiaris Linneaus, 1758 [domestic dog]" and "dingo Meyer, 1793 [domestic dog]",[a] with the comment "Includes the domestic dog as a subspecies, with the dingo provisionally separate – artificial variants created by domestication and selective breeding. Although this may stretch the subspecies concept, it retains the correct allocation of synonyms."[1] Although the earliest use of the name "dingo" was Canis familiaris dingo (Blumenbach, 1780),[37] Wozencraft attributed it to Meyer from 1793 without comment.[38]

This classification by Wozencraft is hotly debated by zoologists.[35] Mathew Crowther, Stephen Jackson and Colin Groves disagree with Wozencraft and argue that based on ICZN Opinion 2027, the implication is that a domestic animal cannot be a subspecies.[39][40] Crowther, Juliet Clutton-Brock and others argue that because the dingo differs from wolves by behavior, morphology, and that the dingo and dog do not fall genetically within any extant wolf clade, that the dingo should be considered the distinct taxon Canis dingo.[41][35][40] Jackson and Groves regard the dog Canis familiaris as a taxonomic synonym for the wolf Canis lupus with them both equally ranked at the species level. They also disagree with Crowther, based on the overlap between dogs and dingoes in their morphology, in their ability to easily hybridize with each other, and that they show the signs of domestication by both having a cranium of smaller capacity than their progenitor, the wolf. Given that Canis familiaris (Linnaeus, 1758) has date priority over Canis dingo (Meyer, 1793), they regard the dingo as a junior taxonomic synonym for the dog Canis familiaris.[39] Gheorghe Benga and others support the dingo as a subspecies of the dog from the earlier Canis familiaris dingo (Blumenbach, 1780).[42][43][44] Xiaoming Wang and Richard H. Tedford proposed that the dog should be classified as Canis lupus familiaris under the Biological Species Concept and Canis familiaris under the Evolutionary Species Concept.[4]`;
const pig = `A typical pig has a large head with a long snout that is strengthened by a special prenasal bone and by a disk of cartilage at the tip.[8] The snout is used to dig into the soil to find food and is a very acute sense organ. There are four hoofed toes on each trotter (foot), with the two larger central toes bearing most of the weight, but the outer two also being used in soft ground.[9]

The dental formula of adult pigs is 
3.1.4.3
3.1.4.3
, giving a total of 44 teeth. The rear teeth are adapted for crushing. In the male, the canine teeth form tusks, which grow continuously and are sharpened by constantly being ground against each other.[8]

Occasionally, captive mother pigs may savage their own piglets, often if they become severely stressed.[10] Some attacks on newborn piglets are non-fatal. Others may cause the death of the piglets and sometimes, the mother may eat the piglets. It is estimated that 50% of piglet fatalities are due to the mother attacking, or unintentionally crushing, the newborn pre-weaned animals.[11]

Scientists have recently discovered that pigs can exhibit a cognitive bias and are optimists or pessimists, similar to humans. In a study by the University of Lincoln, 36 pigs were tested. They were placed in a room with two food bowls at each end of the room. One food bowl contained sugar-coated chocolate sweets and the other contained coffee beans. Optimistic pigs were likely to check if there was a third bowl filled with sweets. However pessimistic pigs would not even bother checking if the bowl was filled with sweets or not. It was said that "Pro-active pigs were willing to see whether there was a positive outcome in the mystery bowl". The study shows that non-human animals can share similar traits with humans.[12]`;
const monkey = `Monkeys are haplorhine primates, a group generally possessing tails and consisting of about 260 known living species. There are two distinct lineages of monkeys: New World Monkeys and catarrhines. Apes emerged within the catarrhines with the Old World monkeys as a sister group, so cladistically they are monkeys as well. However, traditionally apes are not considered monkeys, rendering this grouping paraphyletic. The equivalent monophyletic clade are the simians. Many monkey species are tree-dwelling (arboreal), although there are species that live primarily on the ground, such as baboons. Most species are also active during the day (diurnal). Monkeys are generally considered to be intelligent, particularly Old World monkeys.

Lemurs, lorises, and galagos are not monkeys; instead they are strepsirrhine primates. Like monkeys, tarsiers are haplorhine primates; however, they are also not monkeys. There are two major types of monkey: New World monkeys (platyrrhines) from South and Central America and Old World monkeys (catarrhines of the superfamily Cercopithecoidea) from Africa and Asia. Hominoid apes (consisting of gibbons, orangutans, gorillas, chimpanzees, and humans), which all lack tails, are also catarrhines but are not considered monkeys.[3] (Tailless monkeys may be called "apes", incorrectly according to modern usage; thus the tailless Barbary macaque is sometimes called the "Barbary ape".) Simians ("monkeys") and tarsiers emerged within haplorrhines some 60 million years ago. New World monkeys and catarrhine monkeys emerged within the simians some 35 millions years ago. Old World monkeys and Hominoidea emerged within the catarrhine monkeys some 25 millions years ago. Extinct basal simians such as Aegyptopithecus or Parapithecus [35-32 million years ago] are also considered monkeys by primatologists.`;

module.exports = {dog, cat, pig, monkey};
